version: '3'

services:
  backend:
    build:
      context: ./backend
    image: vue-py:1.0
    container_name: backend_container
    tty: true
    ports:
      - '5000:5000'
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./backend/app:/web/app
    command: 'flask run --host 0.0.0.0 --port 5000'
    #    links:
    #      -
